name: AdaptiveServerCore
version: 1.0.1
main: net.modclaim.asc.platform.spigot.AdaptiveServerCoreSpigotPlugin
api-version: '1.20'
author: ModClaim
description: Adaptive Server Performance Core Plugin for Spigot.
softdepend: [WorldGuard, Chunky, ClearLag, LaggRemover, MythicMobs, PlaceholderAPI, Vault, ProtocolLib]
commands:
  asc:
    description: Adaptive Server Core primary administration command
    permission: asc.admin
    usage: /asc [subcommand]
permissions:
  asc.admin:
    description: Grants access to Adaptive Server Core management commands and GUI
    default: op
