name: AdaptiveServerCore
version: 1.0.0
main: net.modclaim.asc.loader.AdaptiveServerCoreUniversalPlugin
api-version: '1.20'
author: ModClaim
description: Universal Adaptive Server Performance Core Plugin for Paper, Purpur, Folia, and Spigot.
folia-supported: true
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
    Chunky:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
