name: AdaptiveServerCore
version: 1.0.0
main: net.modclaim.asc.platform.paper.AdaptiveServerCorePaperLatestPlugin
api-version: '1.21'
author: ModClaim
description: Adaptive Server Performance Core Plugin optimized for Paper 1.21+ and Folia.
folia-supported: true
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
    Chunky:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
